[package]
name = "test_binance"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "*"
tokio-tungstenite = "*"
serde_json = "*"
eyre = "*"
tokio = {version = "*", features = ["full"]}
serde = {version = "*", features = ["derive"]}
